### ISSUE TITLE
подозрительные импорты

### ISSUE THREAD

**Issue by kuzmichevdima** [ZyryanovI/Python_Game_Life#2]
https://github.com/ZyryanovI/Python_Game_Life/blob/5d557a842d580403e3069992b2e0de3ab89d3b89/test.py#L5-L6

кто такая dasha

**Comment by ZyryanovI** [comment]
Я рассказывал в телеграме, что когда задача почему-то в контест не сдавалась, я проверял что на случайных тестах выдают мой код и другой код, потом забыл удалить просто. Сейчас удалил

**Comment by kuzmichevdima** [comment]
допустим, но почему файлик называется dasha_main ? Кто такая Даша

**Comment by ZyryanovI** [comment]
Филипецкая Дарья.  Файл я так называл для себя, когда пытался понять в чем проблема при сдавании в контест. И я не очень понимаю в чем здесь претензия/проблема
