### ISSUE TITLE
тесты

### ISSUE THREAD

**Issue by kuzmichevdima** [ZyryanovI/Python_Game_Life#4]
https://github.com/ZyryanovI/Python_Game_Life/blob/5d557a842d580403e3069992b2e0de3ab89d3b89/test.py#L176

нужно проверять и другие части кода тоже

**Comment by ZyryanovI** [comment]
Теперь тестируются все функции Game, которые что-то делают(кроме ввода и вывода)

**Comment by kuzmichevdima** [comment]
Нужны тесты на метод update у разных сущностей

**Comment by ZyryanovI** [comment]
Теперь update тестируется у всех сущностей при разных вариантах развития событий
