### ISSUE TITLE
вынести логику в метод

### ISSUE THREAD

**Issue by kuzmichevdima** [ZyryanovI/Python_Game_Life#5]
https://github.com/ZyryanovI/Python_Game_Life/blob/5d557a842d580403e3069992b2e0de3ab89d3b89/main.py#L39-L55

что было бы здесь, если бы видов было штук 10? нужно логику определения того, что теперь находится в клетке, вынести в метод классов (завести для каждого вида класс, наследующийся от какого-то общего).

**Comment by ZyryanovI** [comment]
Исправил
