### ISSUE TITLE
kol

### ISSUE THREAD

**Issue by kuzmichevdima** [ZyryanovI/Python_Game_Life#6]
https://github.com/ZyryanovI/Python_Game_Life/blob/5d557a842d580403e3069992b2e0de3ab89d3b89/main.py#L64

**Comment by ZyryanovI** [comment]
А в чём именно проблема в этой функции?

**Comment by kuzmichevdima** [comment]
в названии kol

**Comment by ZyryanovI** [comment]
Исправил
