### ISSUE TITLE
defaultdict

### ISSUE THREAD

**Issue by kuzmichevdima** [ZyryanovI/Python_Game_Life#7]
https://github.com/ZyryanovI/Python_Game_Life/blob/5d557a842d580403e3069992b2e0de3ab89d3b89/main.py#L15-L18

чтобы не писать самому везде нули, используй collections.defaultdict(int). На семинарах разбирали, что это - по сути тот же dict, только там есть значение по умолчанию, что убирает необходимость инициализации

**Comment by ZyryanovI** [comment]
Исправил

**Comment by kuzmichevdima** [comment]
https://github.com/ZyryanovI/Python_Game_Life/blob/277811ad84fda105558cd023ee5c2a9453fce3c3/CGame.py#L80-L81

в том и суть defaultdict(int), что там есть значение по умолчанию =0. Самому не нужно инициализировать

**Comment by ZyryanovI** [comment]
Исправил
