### ISSUE TITLE
main и main2

### ISSUE THREAD

**Issue by kuzmichevdima** [ZyryanovI/Python_Game_Life#8]
https://github.com/ZyryanovI/Python_Game_Life/blob/5d557a842d580403e3069992b2e0de3ab89d3b89/main2.py#L1

зачем нужны main и main2?

**Comment by ZyryanovI** [comment]
Заменил main2 на CGame(по сути в main2 просто лежал сам класс Game, а в main он же только с кодом, решающим задачу) Из main класс Game убрал
