### ISSUE TITLE
название класса

### ISSUE THREAD

**Issue by kuzmichevdima** [ZyryanovI/Python_Game_Life#9]
https://github.com/ZyryanovI/Python_Game_Life/blob/277811ad84fda105558cd023ee5c2a9453fce3c3/CGame.py#L5

по названию абсолютно не понятно, что это

**Comment by ZyryanovI** [comment]
Теперь называется IObject(не знаю понятнее ли, но надеюсь что да)

**Comment by kuzmichevdima** [comment]
нет, не понятнее. Тем более, в python есть object - база всех классов, так что так же называть свой класс - плохая идея. По названию должно быть понятно, что он представляет. В данном случае вид животных -> можно назвать Animal, Creature, Species или еще как-то.
Приписывать Object к названиям других классов не стоит (RockObject и так далее), зачем?

**Comment by ZyryanovI** [comment]
Исправил
